# Файл docker-compose.yml

# Версия docker-compose
# version: '3'

# Перечень volume
volumes:
  pg_data:
  static:

# Перечень контейнеров
services:
  # Имя и описание первого контейнера; имя выбирает разработчик. 
  # Это контейнер БД
  db:
    # Из какого образа запустить контейнер:
    image: postgres:13.10
    # Файл (или список файлов) с переменными окружения
    env_file: .env
    # Какой volume подключить для этого контейнера
    volumes:
      - pg_data:/var/lib/postgresql/data
  # Имя и описание контейнера с бэкендом
  backend:
    # Из какого Dockerfile собирать образ для этого контейнера:
    # container_name: backend
    image: komarovae/taski_backend
    env_file: .env
    volumes:
      - static:/backend_static
    # Какие контейнеры нужно запустить до старта этого контейнера:
    depends_on:
      - db
  # Имя третьего контейнера. Это контейнер с фронтендом
  frontend:
    image: komarovae/taski_frontend_slim
    env_file: .env
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/

  gateway:
    image: komarovae/taski_gateway
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles
    depends_on:
      - backend